const body=document.body;const menu=document.querySelector('.menu');const nav=document.querySelector('.nav');
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav?.classList.toggle('is-open',open);body.classList.toggle('menu-open',open)});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu?.setAttribute('aria-expanded','false');nav.classList.remove('is-open');body.classList.remove('menu-open')}));
document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
const root=document.querySelector('[data-lightbox-root]');const image=document.querySelector('[data-lightbox-image]');
document.querySelectorAll('[data-lightbox]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();image.src=link.href;image.alt=link.querySelector('img')?.alt||'';root.hidden=false;body.classList.add('menu-open')}));
const close=()=>{if(!root)return;root.hidden=true;image.removeAttribute('src');body.classList.remove('menu-open')};root?.addEventListener('click',e=>{if(e.target===root||e.target.closest('[data-lightbox-close]'))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
if(!document.querySelector('[data-cookie-bar]')){const cookieMarkup='<aside class="cookie-bar" data-cookie-bar hidden><p>Ta strona używa wyłącznie niezbędnych cookies. <a href="cookies.html">Dowiedz się więcej</a> · <button class="cookie-open" data-cookie-open type="button">Ustawienia cookies</button></p><div class="cookie-actions"><button data-cookie-essential type="button">Tylko niezbędne</button><button data-cookie-accept type="button">Akceptuję</button></div></aside><div class="cookie-settings" data-cookie-settings hidden><section class="cookie-dialog" role="dialog" aria-modal="true" aria-labelledby="cookie-title"><h2 id="cookie-title">Ustawienia cookies</h2><p>Wybierz, na co wyrażasz zgodę. Ta wersja strony nie używa cookies analitycznych ani marketingowych.</p><div class="cookie-row"><span>Niezbędne<small>Zawsze aktywne — potrzebne do działania strony.</small></span><input type="checkbox" checked disabled aria-label="Cookies niezbędne"></div><div class="cookie-row"><span>Analityczne<small>Obecnie nieużywane.</small></span><input type="checkbox" disabled aria-label="Cookies analityczne"></div><div class="cookie-actions"><button data-cookie-close type="button">Anuluj</button><button data-cookie-save type="button">Zapisz wybór</button></div></section></div>';document.body.insertAdjacentHTML('beforeend',cookieMarkup)}
const cookieKey='mk-cookie-preferences';const cookieBar=document.querySelector('[data-cookie-bar]');const cookieSettings=document.querySelector('[data-cookie-settings]');const cookieClose=document.querySelector('[data-cookie-close]');const openCookies=()=>{if(cookieSettings)cookieSettings.hidden=false};const hideCookies=()=>{if(cookieBar)cookieBar.hidden=true;if(cookieSettings)cookieSettings.hidden=true};const saveCookies=(value)=>{localStorage.setItem(cookieKey,value);hideCookies()};if(cookieBar&&!localStorage.getItem(cookieKey))cookieBar.hidden=false;document.querySelectorAll('[data-cookie-open]').forEach(button=>button.addEventListener('click',openCookies));document.querySelector('[data-cookie-essential]')?.addEventListener('click',()=>saveCookies('essential'));document.querySelector('[data-cookie-accept]')?.addEventListener('click',()=>saveCookies('all'));document.querySelector('[data-cookie-save]')?.addEventListener('click',()=>saveCookies('custom'));cookieClose?.addEventListener('click',hideCookies);cookieSettings?.addEventListener('click',event=>{if(event.target===cookieSettings)hideCookies()});
